apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: local-path-provisioner
  namespace: kube-system
spec:
  interval: 10m0s
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: local-path-provisioner
    namespace: kube-system
  path: "./deploy"
  prune: true
  timeout: 1m
